name: build-test
on:
  workflow_dispatch: # Enables manually

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CR_PAT: ${{ secrets.CR_PAT }}
      QT_MODULES: 'qtcharts qtserialbus qtserialport qtwebsockets'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install Qt(android)
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          target: android
          arch: android_armv7
          host: linux
          dir: ${{ github.workspace }}
          modules: ${{env.QT_MODULES}}
          version: ${{ matrix.version }}
      - name: Install Qt(linux_gcc_64)
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          target: desktop
          arch: linux_gcc_64
          host: linux
          dir: ${{ github.workspace }}
          modules: ${{env.QT_MODULES}}
          version: ${{ matrix.version }}
      - name: build docker image
        run: |
          docker build -t x-tools-ubuntu-20.04-1:x86_64 . -f docker/20.04-android/Dockerfile \
            --build-arg HOST_QT_ROOT=${{ github.workspace }}/Qt \
            --build-arg HOST_JAVA_HOME=$JAVA_HOME_17_X64 \
            --build-arg HOST_ANDROID_HOME=$ANDROID_HOME \
      - name: push docker image to github registry
        run: |
          echo ${{ env.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker rmi ghcr.io/x-tools-author/x-tools-ubuntu-20.04-1:x86_64 || true
          docker tag x-tools-ubuntu-20.04-1:x86_64 ghcr.io/x-tools-author/x-tools-ubuntu-20.04-1:x86_64
          docker push ghcr.io/x-tools-author/x-tools-ubuntu-20.04-1:x86_64