name: build-test
on:
  workflow_dispatch: # Enables manually

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Pull respository
        uses: actions/checkout@v4
      - name: Build docker image
        shell: cmd
        run: |
          git fetch --tags 
          docker pull ghcr.io/x-tools-author/x-tools-windows-2022:amd64
          docker run --rm --privileged -v ${{ github.workspace }}:/workspace ${{ env.DOCKER_IMAGE }} /bin/bash -c "\
          cd /workspace && ./scripts/ci-build-windows-mingw.bat"