name: build-test
on:
  workflow_dispatch: # Enables manually

jobs:
  build:
    name: Build
    runs-on: windows-2022
    env:
      DOCKER_IMAGE: ghcr.io/x-tools-author/x-tools-windows-2022:amd64
    steps:
      - name: Pull respository
        uses: actions/checkout@v4
      - name: Build docker image
        shell: cmd
        run: |
          git fetch --tags 
          docker pull ${{ env.DOCKER_IMAGE }}
          call ${{ env.DOCKER_IMAGE }}\scripts\win-path-to-linux-path.bat
          echo %%WORKSPACE_UNIX%%
          docker run --rm -v %WORKSPACE_UNIX%:/workspace ${{ env.DOCKER_IMAGE }} cmd /c "\
          cd /workspace && scripts/ci-build-windows-mingw.bat"