name: build-test
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Enables manually

env:
  QT_VERSION: 6.8.3
  UBUNTU_VERSION: 20.04

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{ env.QT_VERSION }}
          target: 'desktop'
          arch: linux_gcc_64
          dir: ${{ github.workspace }}
          modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
      - name: pull ubuntu docker image
        run: |
          docker pull ubuntu:${{ env.UBUNTU_VERSION }}
      - name: run docker container
        run: |
          docker run -d --name ubuntu-${{ env.UBUNTU_VERSION }} -v ${{ github.workspace }}:/workspace ubuntu:${{ env.UBUNTU_VERSION }} tail -f /dev/null
      - name: install dependencies
        run: |
          docker exec -it ubuntu-${{ env.UBUNTU_VERSION }} bash -c "apt -y install software-properties-common"
          docker exec -it ubuntu-${{ env.UBUNTU_VERSION }} bash -c "add-apt-repository ppa:deadsnakes/ppa -y"
          docker exec -it ubuntu-${{ env.UBUNTU_VERSION }} bash -c "apt update"
          docker exec -it ubuntu-${{ env.UBUNTU_VERSION }} bash -c "apt -y install python3.13"