name: build-test
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Enables manually

env:
  QT_VERSION: 6.8.3
  UBUNTU_VERSION: 22.04

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{ env.QT_VERSION }}
          target: 'desktop'
          arch: linux_gcc_64
          dir: ${{ github.workspace }}
          modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
      - name: install-dependencies
        run: |
          sudo apt-get install -y libxcb-xinerama0 libxcb-cursor-dev  libudev-dev libusb-dev libusb-1.0-0-dev
      - name: build for linux
        run: |
          git fetch --tags
          cmake --version
          mkdir build
          cd build
          cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/linux_gcc_64' -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../
          cmake --build . --target xTools --config Release --parallel 8 --verbose