name: build-test
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Enables manually
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Start and setup Ubuntu container
        run: |
          docker pull ubuntu:20.04
          docker run  ubuntu:20.04 bash -c apt update
          docker run  ubuntu:20.04 bash -c apt install -y python3 python3-pip python3-dev
          docker run  ubuntu:20.04 bash -c apt install -y libxcb-xinerama0 libxcb-cursor-dev libudev-dev libusb-dev libusb-1.0-0-dev
          docker run  ubuntu:20.04 bash -c apt install -y git

