name: build-test
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Enables manually
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Ubuntu image
        run: docker pull ubuntu:22.04
      - name: Start Ubuntu container
        run: docker run -d --name ubuntu-22.04 ubuntu:22.04 sleep infinity
      - name: Update and install Python
        run: docker exec ubuntu-22.04 bash -c "apt-get update && apt-get install -y python3 python3-pip python3-dev"
      - name: Install additional dependencies
        run: docker exec ubuntu-22.04 bash -c "apt-get install -y libxcb-xinerama0 libxcb-cursor-dev libudev-dev libusb-dev libusb-1.0-0-dev git"
      - name: Verify Python installation
        run: docker exec ubuntu-22.04 bash -c "python3 --version && pip3 --version"
      - name: Install qtinstall
        run: docker exec ubuntu-22.04 bash -c "pip install aqtinstall"
      - name: Install Qt
        run: docker exec ubuntu-22.04 bash -c "aqt install-qt linux desktop 6.8.3 linux_gcc_64 -m qtcharts qtserialbus qtserialport qtwebsockets"