name: build-test
on:
  workflow_dispatch: # Enables manually

jobs:
  build:
    name: Build
    runs-on: windows-2022
    env:
      DOCKER_IMAGE: ghcr.io/x-tools-author/x-tools-windows-2022:amd64
    steps:
      - name: Pull Respository
        uses: actions/checkout@v4
      - name: Pull Image
        if: false
        run: |
           docker pull ${{ env.DOCKER_IMAGE }}
      - name: Build docker image
        shell: cmd
        run: |
          git fetch --tags 
          echo ${{ github.workspace }}
