name: build-test
on:
  workflow_dispatch: # Enables manually

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Pull respository
        uses: actions/checkout@v4
      - name: Build docker image
        shell: cmd
        run: | #https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
          dir c:
          echo %%PATH%%