name: build-test
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Enables manually

env:
  QT_VERSION: 6.8.3
  UBUNTU_VERSION: 20.04

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: pull ubuntu docker image
        run: |
          docker pull ubuntu:${{ env.UBUNTU_VERSION }}
      - name: run docker container
        run: |
          docker run -d --name ubuntu-${{ env.UBUNTU_VERSION }} -v ${{ github.workspace }}:/workspace ubuntu:${{ env.UBUNTU_VERSION }} tail -f /dev/null
      - name: install dependencies
        run: |
          docker exec -i ubuntu-${{ env.UBUNTU_VERSION }} bash -c "apt-get update"
          docker exec -i ubuntu-${{ env.UBUNTU_VERSION }} bash -c "apt-get -y install software-properties-common"
          docker exec -i ubuntu-${{ env.UBUNTU_VERSION }} bash -c "add-apt-repository ppa:deadsnakes/ppa -y"
          docker exec -i ubuntu-${{ env.UBUNTU_VERSION }} bash -c "apt-get update"
          docker exec -i ubuntu-${{ env.UBUNTU_VERSION }} bash -c "apt-get -y install python3.13"