name: build-test
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Enables manually

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build docker image
        run: |
          docker build -t x-tools:ubuntu-22.04 .