name: build-qt5
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Enables manually
# on:
#  push:
#    branches:
#      - master
jobs:
  build:
    name: Build with Qt5
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        version: [5.15.2]
        arch: [win64_msvc2019_64]
    steps:
      - name: Pull code
        uses: actions/checkout@v4
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          dir: ${{ github.workspace }}
          version: ${{ matrix.version }}
          target: desktop
          arch: ${{ matrix.arch }}
          modules: 'qtcharts'
      - name: build-msvc
        shell: cmd
        run: |
          mkdir build
          cd build
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/${{ matrix.version }}/${{ matrix.arch }}' -DCMAKE_BUILD_TYPE=Release -G "Ninja" ../
          cmake --build . --target all --config Release
